language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
  - ffprobe -version

# command to install dependencies
install:
  - pip install -r requirements.txt

after_success:
  -  coveralls

# command to run tests
script: python -m pytest -s
